name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: guinnessshep
        password: dckr_pat_aBq-3fQzd2Y3-HeQgRTRkae0LmQ

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile.backend
        push: true
        tags: user/myapp-backend:latest

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.frontend
        push: true
        tags: user/myapp-frontend:latest

    - name: Build and Push Golang Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./golang
        file: ./golang/Dockerfile.golang
        push: true
        tags: user/myapp-golang:latest
